version: '3.8'
services:
 notebook:
   image: jupyter/scipy-notebook
   ports:
     - "9988:8888"
   volumes:
     - ./notebooks:/home/jovyan/work
     - ./data:/home/jovyan/data
   environment:
     JUPYTER_ENABLE_LAB: "yes"
 mongo:
   image: mongo:latest
   container_name: mongodb
   restart: always
   ports:
     - "27017:27017"
   environment:
     MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
     MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
   volumes:
     - mongo_data:/data/db
 mongo-express:
   image: mongo-express:latest
   container_name: mongo-express
   restart: always
   depends_on:
     - mongo
   ports:
     - "8081:8081"
   environment:
     ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
     ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
     ME_CONFIG_MONGODB_SERVER: mongo
     ME_CONFIG_MONGODB_URL: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/
     ME_CONFIG_BASICAUTH: "false"
 etl:
    image: python:3.10
    container_name: etl-script
    command: sh -c "pip install pandas pymongo watchdog && python /app/etl.py"
    volumes:
      - ./etl:/app
      - ./data:/app/data
    environment:
      MONGO_URI: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017
    depends_on:
      - mongo
volumes:
 mongo_data: